service: hyperflow-awslambda-executor

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 2048
  timeout: 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::todo/*"

package:
  exclude:
    - .idea/**
    - node_modules/**
  include:
    - node_modules/async/**
    - node_modules/lodash/**

functions:
  executor:
    handler: handler.executor
    events:
      - http:
          path: executor
          method: get
      - http:
          path: executor
          method: post