service: hyperflow-awslambda-executor

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  memorySize: 512
  timeout: 60

package:
  exclude:
    - .idea/**
    - node_modules/**
  include:
    - node_modules/async/**
    - node_modules/lodash/**

functions:
  executor:
    handler: handler.executor
    events:
      - http:
          path: executor
          method: get
      - http:
          path: executor
          method: post